//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerResult
    {
        public int Id { get; set; }
        public int ResultId { get; set; }
        public int QuestionAnswerId { get; set; }
    
        public virtual QuestionAnswer QuestionAnswer { get; set; }
        public virtual Result Result { get; set; }
    }
}
