
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quiz.DAL.EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class QuizOption
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuizOption()
    {

        this.QuizSessions = new HashSet<QuizSession>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int Amount { get; set; }

    public decimal RequiredPercentage { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuizSession> QuizSessions { get; set; }

}

}
